######################################################################
# Automatically generated by qmake (3.0) Wed Feb 11 15:30:50 2015
######################################################################

CONFIG += c++11 debug
QT += testlib
TEMPLATE = app
TARGET = testrunner
INCLUDEPATH += .

# Input
HEADERS += global.h piece.h position.h testpiece.h testposition.h
SOURCES += piece.cpp position.cpp testpiece.cpp testposition.cpp testrunner.cpp
