######################################################################
# Automatically generated by qmake (3.0) Wed Feb 11 15:30:50 2015
######################################################################

CONFIG += c++14
QT += testlib
TEMPLATE = app
TARGET = shogi-bod
INCLUDEPATH += .

# Input
HEADERS += global.h piece.h testpiece.h
SOURCES += piece.cpp testpiece.cpp
